### ISSUE TITLE
No metrics when switch the language

### ISSUE THREAD

**Issue by orazionelson** [pkp/paperbuzz#3] opened 2016-04-19 10:34 UTC
Hello,
I installed the ALM plugin and everything works fine but metrics appear only if the language is English, with Italian there is only the loading message.

You can try here switching the languages:
http://www.rmojs.unina.it/index.php/rm/article/view/305

How to see metrics also in Italian?

Tnx

**Comment by asmecher** [comment] 2016-04-19 18:19
(FYI @jalperin and @jnugent)

**Comment by orazionelson** [comment] 2016-04-28 10:45
One more thing:
-the site default language is italian
-if I set any language other than Italian I see the metrics

tnx
A.

**Comment by jalperin** [comment] 2016-04-28 16:17
This is one for @beghelli, I think, who has been more actively involved in the ALM OJS plugin.

**Comment by hermannschwaerzlerUIBK** [comment] 2016-04-28 20:11
As far as I can see (in my firebug console) the problem is this:
```
SyntaxError: missing } after property list
	...xt: 'Citazioni dell'articolo trovate in CrossRef, PubMed e Wikipedia. In molti 
```
Changing `plugins/generic/alm/locale/it_IT/locale.xml` line 41 by adding a \ before that ' in `dell'articolo` (i.e. `dell\'articolo`) did do the trick for me...

Greetings
Hermann

**Comment by orazionelson** [comment] 2016-04-29 10:30
It works!
tnx

**Comment by beghelli** [comment] 2016-04-30 01:55
Hi @orazionelson and @hermannschwaerzlerUIBK , can you double check that your plugins/generic/alm/output.tpl file, line 39, is equal to this one:

`{ldelim} name: "citations", display_name: '{translate key="plugins.generic.alm.categories.citations"}', tooltip_text: '{translate key="plugins.generic.alm.categories.citations.description"|escape:"jsparam"}' {rdelim}],`

As you can see, it's already being escaped. Let me know what you have.

Cheers.

**Comment by orazionelson** [comment] 2016-04-30 09:18
It is equal

**Comment by hermannschwaerzlerUIBK** [comment] 2016-05-01 10:31
Same here. That's exactly the line I see in my **plugins/generic/alm/output.tpl**.
But looking at the smarty-code (namely **lib/pkp/lib/smarty/plugins/modifier.escape.php**) I do not see an escape-format named _jsparam_. There is one named _javascript_ (which escapes "quotes and backslashes, newlines, etc.") though. Is this the one that should be used?

On the other hand the _jsparam_ format is used 132 times whereas the _javascript_ format is used 60 times in my installation so I reckon I am missing something...

**Comment by hermannschwaerzlerUIBK** [comment] 2016-05-02 09:15
Some new "findings":
I changed plugins/generic/alm/locale/it_IT/locale.xml back to its original content and looked what I can see:
Escaping works:
```
grep -r 'Citazioni dell' cache/
cache/fc-locale-df1758eca6c5e9f5cbea87997c5dce4a.php:  'plugins.generic.alm.categories.citations.description' => 'Citazioni dell\'articolo trovate in CrossRef, PubMed e Wikipedia. In molti casi, cliccando sul numero delle condivisioni, verrai trasferito alla lista sul servizio citazionale stesso.',
```
But that just means that in the output of the translate-function of smarty the \' becomes a ' again, doesn't it?
What did help was changing ' to " around `{translate ...}`:
```
tooltip_text: '{translate key="plugins.generic.alm.categories.citations.description"|escape:"jsparam"}'
```
to
```
tooltip_text: "{translate key="plugins.generic.alm.categories.citations.description"|escape:"jsparam"}"
```
Looks like smarty takes anything outside `{translate ...}` literally without considering " or ' as quoting characters?
So I think you have to be aware of that and have to escape the quoting-character you chose in the template inside the locale-file - whichever it was...

**Comment by beghelli** [comment] 2016-05-02 10:43
Hi Hermann,

Thanks yo so much for your investigation.

From what you're telling, it seems that the ' character is not being
escaped at all, even if the smarty template cache shows differently. The '
character matches the one used to hold the tooltip_text string. When you
adopt " to hold that string that has a ', then the js code runs ok because
they do not clash.

I will take a closer look to the jsparam method.

Thanks again,
Bruno

2016-05-02 6:15 GMT-03:00 Hermann Schwärzler <notifications@github.com>:

**Comment by NateWr** [comment] 2019-04-09 13:15
Closing as outdated.

**Closed by NateWr** 2019-04-09 13:15 UTC
